In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Activation, BatchNormalization, Conv2D, MaxPool2D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import regularizers
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
import itertools
import os
import shutil
import random
import glob
import matplotlib.pyplot as plt
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
%matplotlib inline

In [2]:
model3 = keras.models.load_model('models/model3.keras')

import pickle
def unpickle(file):
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
    return dict

test_batch = unpickle('cifar-10-batches-py/test_batch')
X = test_batch[b'data']
y_true = test_batch[b'labels']

X = X.reshape(-1, 3, 32, 32).transpose(0, 2, 3, 1).astype('float32') / 255.0

y_true_categorical = keras.utils.to_categorical(y_true, num_classes=10)

test_loss, test_accuracy = model3.evaluate(X, y_true_categorical, verbose=1)
print(f'\nTest accuracy: {test_accuracy:.4f}')

predictions = model3.predict(X)
predicted_classes = np.argmax(predictions, axis=1)

cm = confusion_matrix(y_true, predicted_classes)
print('\nConfusion Matrix:')
print(cm)
print(cm)

313/313 ━━━━━━━━━━━━━━━━━━━━ 6s 18ms/step - accuracy: 0.7364 - loss: 1.0598

Test accuracy: 0.7363
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step

Confusion Matrix:
[[741  14  71  29  22   5   9  17  58  34]
 [ 10 860  11   6   4   3   7   5  23  71]
 [ 54   2 608  54  90  75  65  37   7   8]
 [ 11   3  81 531  57 195  62  39  10  11]
 [ 20   3  74  53 654  36  48 102   8   2]
 [  7   0  48 144  41 667  19  63   2   9]
 [  5   3  48  54  30  23 822  12   2   1]
 [ 10   3  38  34  30  60   3 816   2   4]
 [ 58  27  13  25   8   4   4   7 831  23]
 [ 25  68   7  20   5   8   3  11  20 833]]
[[741  14  71  29  22   5   9  17  58  34]
 [ 10 860  11   6   4   3   7   5  23  71]
 [ 54   2 608  54  90  75  65  37   7   8]
 [ 11   3  81 531  57 195  62  39  10  11]
 [ 20   3  74  53 654  36  48 102   8   2]
 [  7   0  48 144  41 667  19  63   2   9]
 [  5   3  48  54  30  23 822  12   2   1]
 [ 10   3  38  34  30  60   3 816   2   4]
 [ 58  27  13  25   8   4   4   7 831  23]
 [ 25  68   7  20   5 

In [3]:
model2 = keras.models.load_model('models/model2.keras')

import pickle
def unpickle(file):
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
    return dict

test_batch = unpickle('cifar-10-batches-py/test_batch')
X = test_batch[b'data']
y_true = test_batch[b'labels']

X = X.reshape(-1, 3, 32, 32).transpose(0, 2, 3, 1).astype('float32') / 255.0

y_true_categorical = keras.utils.to_categorical(y_true, num_classes=10)

test_loss, test_accuracy = model2.evaluate(X, y_true_categorical, verbose=1)
print(f'\nTest accuracy: {test_accuracy:.4f}')

predictions = model2.predict(X)
predicted_classes = np.argmax(predictions, axis=1)

cm = confusion_matrix(y_true, predicted_classes)
print('\nConfusion Matrix:')
print(cm)
print(cm)

313/313 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step - accuracy: 0.7515 - loss: 0.8228

Test accuracy: 0.7510
313/313 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step

Confusion Matrix:
[[806   8  45  24  16  10   7  12  40  32]
 [ 20 822  11   7   1   1   6   5  13 114]
 [ 66   4 629  59  80  61  55  31   7   8]
 [ 23   3  62 569  65 172  45  34  13  14]
 [ 19   2  75  75 685  34  36  62  11   1]
 [ 12   4  56 167  25 667  16  40   7   6]
 [  9   3  27  65  32  34 807   7   8   8]
 [ 11   1  26  33  46  44   3 822   2  12]
 [ 61  19  12  14   5   8   4   4 844  29]
 [ 30  47   8  10   4   8   3  13  18 859]]
[[806   8  45  24  16  10   7  12  40  32]
 [ 20 822  11   7   1   1   6   5  13 114]
 [ 66   4 629  59  80  61  55  31   7   8]
 [ 23   3  62 569  65 172  45  34  13  14]
 [ 19   2  75  75 685  34  36  62  11   1]
 [ 12   4  56 167  25 667  16  40   7   6]
 [  9   3  27  65  32  34 807   7   8   8]
 [ 11   1  26  33  46  44   3 822   2  12]
 [ 61  19  12  14   5   8   4   4 844  29]
 [ 30  47   8  10   4 

In [4]:
model1 = keras.models.load_model('models/model1.keras')

import pickle
def unpickle(file):
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
    return dict

test_batch = unpickle('cifar-10-batches-py/test_batch')
X = test_batch[b'data']
y_true = test_batch[b'labels']

X = X.reshape(-1, 3, 32, 32).transpose(0, 2, 3, 1).astype('float32') / 255.0

y_true_categorical = keras.utils.to_categorical(y_true, num_classes=10)

test_loss, test_accuracy = model1.evaluate(X, y_true_categorical, verbose=1)
print(f'\nTest accuracy: {test_accuracy:.4f}')

predictions = model1.predict(X)
predicted_classes = np.argmax(predictions, axis=1)

cm = confusion_matrix(y_true, predicted_classes)
print('\nConfusion Matrix:')
print(cm)
print(cm)

313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - accuracy: 0.7390 - loss: 0.8813

Test accuracy: 0.7345
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step

Confusion Matrix:
[[705  20  81  21  38  13   8   5  49  60]
 [  8 827   4   8   5  13  10   6  15 104]
 [ 39  10 664  46  83  78  37  30   5   8]
 [ 10   5  77 537  74 207  44  24   8  14]
 [  8   2  71  42 736  48  34  48   9   2]
 [  8   4  42 131  46 714  17  30   4   4]
 [  2   3  55  53  51  35 785   7   7   2]
 [  5   4  44  37  74  92  11 721   3   9]
 [ 40  25  26  17  19  11   5   7 818  32]
 [ 12  73   8  17   2   9  10  16  15 838]]
[[705  20  81  21  38  13   8   5  49  60]
 [  8 827   4   8   5  13  10   6  15 104]
 [ 39  10 664  46  83  78  37  30   5   8]
 [ 10   5  77 537  74 207  44  24   8  14]
 [  8   2  71  42 736  48  34  48   9   2]
 [  8   4  42 131  46 714  17  30   4   4]
 [  2   3  55  53  51  35 785   7   7   2]
 [  5   4  44  37  74  92  11 721   3   9]
 [ 40  25  26  17  19  11   5   7 818  32]
 [ 12  73   8  17   2 